<?php
namespace Xlab;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-05 at 14:53:41.
 */
class ProductsManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ProductsManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProductsManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Xlab\ProductsManager::a
     * @todo   Implement testA().
     */
    public function testA()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Xlab\ProductsManager::showProducts
     * @todo   Implement testShowProducts().
     */
    public function testShowProducts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
